# netlify.toml (use when Netlify UI Base directory = "front-end")

#[build.environment]
#  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_SERVICE_ROLE_KEY,SUPABASE_URL,NUXT_SUPABASE_URL,NUXT_SITE_BASE_URL,NUXT_UMAMI_HOST,NUXT_UMAMI_ID,NUXT_SUPABASE_ANON_KEY,NUXT_SITE_DOMAIN"
#  SECRETS_SCAN_OMIT_PATHS = "public/videos/**,.nuxt/**,.output/**,.netlify/**,dist/**"


# netlify.toml (place at repo root)
[build]
  base    = "front-end"
  command = "npm ci && npm run build"
  publish = ".output/public"

[functions]
  # functions path relative to repo root (Netlify expects repo-root path)
  directory = "front-end/.output/server"

[dev]
  command = "npm run --prefix front-end dev"
